### ISSUE TITLE
How to  remove this theme?

### ISSUE THREAD

**Issue by fansuregrin** [yeyushengfan258/Glory-icon-theme#1]
I'm a newbie and just new to Linux，and I want to know how to remove this icon theme. Now I really like this set of icons, I'm just curious how to uninstall it.

Thank you for answering my questions!

**Comment by yeyushengfan258** [comment]
Hello, you need to system settings, find the icon in the Icon bar, you can uninstall

**Comment by fansuregrin** [comment]
> Hello, you need to system settings, find the icon in the Icon bar, you can uninstall

OK! Thank you!

**Comment by fansuregrin** [comment]
OK! Thank you! I will try it.&nbsp;


 
---Original---
